added name to readme
fjord-tracks/bragi-mix pull request #2
Opened 2023-03-03 10:51 UTC by alexvedt

I just added my name to the read-me

2023-03-03 10:54 UTC, S3ak requested changes

2023-03-03 10:54 UTC, S3ak commented on README.md
> +- Alexander Bjerketvedt (@alexvedt)
Nice! But make sure this is your github username

2023-03-03 10:54 UTC, alexvedt commented on README.md
> +- Alexander Bjerketvedt (@alexvedt)
done

2023-03-07 15:40 UTC, S3ak approved these changes

2023-03-07 15:40 UTC, merged