Get rand track
fjord-tracks/bragi-mix pull request #3
Opened 2023-03-03 10:51 UTC by AliNough

Adde my name to readme

2023-03-03 10:53 UTC, S3ak requested changes

2023-03-03 10:53 UTC, S3ak commented on README.md
> +- Ali(@_your_github_username_)
Please put your full name

2023-03-07 15:36 UTC, S3ak requested changes
PLease review my comments and make changes so I can merge this in

2023-03-08 18:47 UTC, AliNough commented on README.md
> +- Ali Nough(@AliNough)
Done

2023-03-08 18:48 UTC, AliNough commented on css/RandStyling.css
> +/* this is an empty css file */
Removed the file and linked randSong.html to original styling file

2023-03-08 18:50 UTC, AliNough commented on main.js
> +  randNavContainerEl.innerHTML = `
i'm confused isn't it already using "is-hidden"?

2023-03-08 18:50 UTC, AliNough commented on style.css
> +@import "/css/RandStyling.css";
Removed this import

2023-03-08 18:52 UTC, AliNough commented on js/randomize.js
> +  <h3>rand.nr: ${randNum}. Year input: ${yrInput}</h3>
Its already commented but it generates a random number between 0 - 20

2023-03-08 18:53 UTC, AliNough commented on js/randomize.js
> +  <h3>rand.nr: ${randNum}. Year input: ${yrInput}</h3>
I changed it to 0 - 19 for now but later it should be replaced with maximum number of results

2023-03-09 08:13 UTC, S3ak approved these changes

2023-03-09 08:16 UTC, merged